### PR TITLE
[New Feature] Save settings support

### PR DESCRIPTION
**Pull request by chraac**
# Save settings support

## Changes:
1. Add save button to save the applied settings (frequency, voltage, freq lock etc.).
2. Load saved settings in app startup automatically (Just load into ongoing setting, will not applied).
3. Unified the Apply button, this means you can change all values then apply once.
4. Add unit test for some class, add circle ci pipeline config.

## Reference
1. [Issue #1: Rearrange the UI and merge the apply button](https://github.com/FIFARenderZ/EPYC-Rome-Overclock/issues/1)

### CODE REVIEW

**Comment by chraac** [comment]
@FIFARenderZ plz take a look.

**Comment by FIFARenderZ** [comment]
Yup, looks good to me. Do you own an engineering sample yourself to do testing on?

**Comment by chraac** [comment]
> Yup, looks good to me. Do you own an engineering sample yourself to do testing on?

Yep, Tested with my 32 cores Rome ES, runs well.

**Comment by FIFARenderZ** [comment]
> Yep, Tested with my 32 cores Rome ES, runs well.
Awesome, thanks for your work!

**Comment by chraac** [comment]
Emm, I think you should fix the pipeline badge in readme.md.

**Comment by FIFARenderZ** [comment]
Oh you're right, will do

**Comment by FIFARenderZ** [comment]
Not sure why, but I can't get CircleCi to build the project correctly. I'm able to build and run it locally just fine. Keeps giving me this error:

`CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /platform:anycpu32bitpreferred /errorreport:prompt /warn:4 /define:DEBUG;TRACE /main:RomeOverclock.Program /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\mscorlib.dll" /reference:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\System.Buffers.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Deployment.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Drawing.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Management.dll" /reference:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\System.Memory.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Numerics.dll" /reference:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\System.Numerics.Vectors.dll" /reference:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\System.ValueTuple.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Windows.Forms.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\RomeOverclock.exe /subsystemversion:6.00 /resource:obj\Debug\RomeOverclock.MainForm.resources /resource:obj\Debug\RomeOverclock.Properties.Resources.resources /target:winexe /warnaserror+ /utf8output /win32icon:Resources/icon.ico /win32manifest:app.manifest /deterministic+ /langversion:7.3 CoreListItem.cs FrequencyListItem.cs MainForm.cs MainForm.Designer.cs smu\OpenLibSys.cs Program.cs Properties\AssemblyInfo.cs smu\SMU.cs smu\SettingManager.cs Properties\Resources.Designer.cs Properties\Settings.Designer.cs "obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn
C:\Users\circleci\project\RomeOverclock\smu\SettingManager.cs(9,19): error CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?) [C:\Users\circleci\project\RomeOverclock\RomeOverclock.csproj]
Done Building Project "C:\Users\circleci\project\RomeOverclock\RomeOverclock.csproj" (default targets) -- FAILED.`

**Comment by chraac** [comment]
> Not sure why, but I can't get CircleCi to build the project correctly. I'm able to build and run it locally just fine. Keeps giving me this error:
> 
> `C:\Users\circleci\project\RomeOverclock\smu\SettingManager.cs(9,19): error CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)`

It's weird, seems the compiler doesn't find the Json package which buildin net framework.

**Comment by chraac** [comment]
I think the compiling error is cause by the erroneous version of ```System.Text.Json```, so can you try delete the ref in IDE and re-add it?

**Comment by FIFARenderZ** [comment]
Sorry for the late reply. Not sure what's going on tbh. It seems like two different Json packages are coliding, but there's no second Json package installed?

**Comment by chraac** [comment]
> Sorry for the late reply. Not sure what's going on tbh. It seems like two different Json packages are coliding, but there's no second Json package installed?

I see you have change the version of ```System.Text.Json``` from ```4.0.1.0``` to ```5.0.0.1``` and add a lot of deps in commit ```b36d2a938e252946de545f45334c9369dc7c1026 ```, maybe you can try to revert it.

In another version you try to use ```Newtonsoft.Json``` to serialization, I think maybe we could stay at ```System.Text.Json``` cause it's dotnet buildin lib.

**Pull request merged**
